-- CreateTable
CREATE TABLE "Reactor" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "generationMw" INTEGER NOT NULL DEFAULT 1000,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "selfDestroy" BOOLEAN NOT NULL DEFAULT false
);
